name: PR Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  agent-analysis:
    runs-on: ubuntu-latest
    steps:
        - uses: VitoorFranca/pr-analysis@master
          with:
            greeting: 'Hello World'
            ignore-paths: |
              **/*.md
              dist/**
