name: PR Pipeline

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  agent-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: VitoorFranca/pr-analysis@master
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          ignore-paths: |
            **/*.tsx